/* tslint:disable */
/* eslint-disable */
/**
 * API CINEMAX
 * API FOR A CINEMA TICKETS PURCHASE SITE
 *
 * The version of the OpenAPI document: v1
 * Contact: suelytonsouza0202@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

